require_relative 'src/tuple.rb'
require_relative 'src/canvas.rb'
require_relative 'src/matrix.rb'
require_relative 'src/transformations.rb'
require_relative 'src/spehe.rb'
require_relative 'src/ray.rb'